version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: "/codebuild/docker/username"
    DOCKER_PASSWORD: "/codebuild/docker/password"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - echo Building Docker image...
      - docker build -t hxbeeb11/sample-app:latest .

  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push hxbeeb11/sample-app:latest
      - echo Build completed successfully.

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
